force-app/main/default/objects/PersonDetail__c/PersonDetail__c.object-meta.xml
<CustomObject>
    <label>PersonDetail</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PersonDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PersonDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonDetail__c/fields/ParentAccount__c.field-meta.xml
<CustomField>
    <fullName>ParentAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentAccount</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PersonDetails</relationshipLabel>
    <relationshipName>PersonDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonDetail__c/fields/PersonEmployeeID__c.field-meta.xml
<CustomField>
    <fullName>PersonEmployeeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PersonEmployeeID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonDetail__c/fields/PersonPhone__c.field-meta.xml
<CustomField>
    <fullName>PersonPhone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PersonPhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/TriggerHandler.cls
public class TriggerHandler {    
    public static void handleAfterInsert(List<Account> acc){
        List<PersonDetail__c> newList = new List<PersonDetail__c>();
        for(Account a : acc){
            PersonDetail__c newObj = new PersonDetail__c();
            newObj.Name = a.Name;
            newObj.PersonPhone__c = a.Phone;
            newObj.PersonEmail__c = a.Email__c;
            newObj.Description__c = a.Description;
            newobj.PersonEmployeeID__c = (String)a.Id;
            newObj.ParentAccount__c = a.ParentId;
            newList.add(newObj);
        }
        insert newList;
    }
   
}