force-app/main/default/objects/Software_Developer__c/Software_Developer__c.object-meta.xml
<CustomObject>
    <label>Software Developer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Software Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Software Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Software_Developer__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Organization</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeveloperTriggerHandlder.cls
public class DeveloperTriggerHandlder{
    public static void fillOrganizationField(List<Software_Developer__c> devList){
        Map<String, Schema.SObjectType> describeResult = Schema.getGlobalDescribe();
        for(Schema.SObjectField strFld : describeResult.get('Software_Developer__c').getDescribe().fields.getMap().values()){
            System.debug(strFld.getDescribe().getLabel());
            if(strFld.getDescribe().getLabel()=='Organization'){
                for(Software_Developer__c dev : devList){
                     dev.Organization__c = 'Mirketa';
                }
            }
        }
    }
}